// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOlaNwwHJIhLxCFufciYuFwPdpbaHjc-U',
    appId: '1:1039619163878:web:d214a619a4893f9bd49d27',
    messagingSenderId: '1039619163878',
    projectId: 'padelpush-app',
    authDomain: 'padelpush-app.firebaseapp.com',
    storageBucket: 'padelpush-app.firebasestorage.app',
    measurementId: 'G-MB012SGECR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOyGbl8yodFfLxeXDhoniCpmcHCGkmaDQ',
    appId: '1:1039619163878:android:e2211b4ce05acc1ed49d27',
    messagingSenderId: '1039619163878',
    projectId: 'padelpush-app',
    storageBucket: 'padelpush-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG4ohebl8-EL2S8Hb5HbIYkHiolQtHO6U',
    appId: '1:1039619163878:ios:f6a305a1200e1ba6d49d27',
    messagingSenderId: '1039619163878',
    projectId: 'padelpush-app',
    storageBucket: 'padelpush-app.firebasestorage.app',
    iosBundleId: 'com.example.padelpush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG4ohebl8-EL2S8Hb5HbIYkHiolQtHO6U',
    appId: '1:1039619163878:ios:f6a305a1200e1ba6d49d27',
    messagingSenderId: '1039619163878',
    projectId: 'padelpush-app',
    storageBucket: 'padelpush-app.firebasestorage.app',
    iosBundleId: 'com.example.padelpush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOlaNwwHJIhLxCFufciYuFwPdpbaHjc-U',
    appId: '1:1039619163878:web:84a287ccb7177c85d49d27',
    messagingSenderId: '1039619163878',
    projectId: 'padelpush-app',
    authDomain: 'padelpush-app.firebaseapp.com',
    storageBucket: 'padelpush-app.firebasestorage.app',
    measurementId: 'G-7VP5EJDZB6',
  );
}
